### ISSUE TITLE
OTP21 logger

### ISSUE THREAD

**Issue by k32** [tolbrino/hut#12]
Hello,

Do you think it is possible to support OTP21's new `logger`?

http://erlang.org/doc/apps/kernel/logger_chapter.html

https://ferd.ca/erlang-otp-21-s-new-logger.html

**Comment by tolbrino** [comment]
Definitely, I just didn't have the time yet. So feel free to send a PR if you like.

**Comment by k32** [comment]
Thanks for the answer, will do

**Comment by tolbrino** [comment]
I guess it would make sense to simply replace `error_logger` with `logger` for OTP 21 as the default.

**Comment by k32** [comment]
The PR is ready for review. I took the liberty of bumping the version, as it changes the default behaviour.

**Comment by k32** [comment]
Hello again, @tolbrino 

Could you please bump version in hex?
