### ISSUE TITLE
Rebar2 incompatibility in OTP24

### ISSUE THREAD

**Issue by masoudgs** [tolbrino/hut#18]
Hi @tolbrino, Hope you're safe and well.

[`bamboo_smtp`](https://github.com/fewlinesco/bamboo_smtp) package is already dependent on `hut@1.3.0` and on the other hand OTP24+ no longer supports rebar2.

**Sample Warning**
```
dependency :hut is using Rebar 2, which is no longer maintained and no longer works in recent Erlang/OTP versions. Remove the :manager option or set it to :rebar3 instead
```

What's your thought on this and is it possible to get rid of this warning by suggested message?

**Comment by alexandremcosta** [comment]
Doesn't this work for you?
```elixir
      {:hut, "~> 1.3", manager: :rebar3, override: true},
```

**Comment by masoudgs** [comment]
Thanks @alexandremcosta, It worked and the warning disappeared.

**Comment by fkrause98** [comment]
Is there a way to solve this without using override?

**Comment by tolbrino** [comment]
I've published a new version which should default to using `rebar3` as the manager.

See https://hex.pm/packages/hut/1.4.0

However, you will still need to overwrite the version in your top-level app. `gen_smtp` has removed the dependency on `hut` in the dev version, so the overwrite will become obsolete once that has been released.

**Comment by fkrause98** [comment]
Thanks!

**Comment by msudgh** [comment]
@tolbrino can I consider this issue as
