### ISSUE TITLE
Publish Hex Package

### ISSUE THREAD

**Issue by mmmries** [tolbrino/hut#2]
Hi. I'm working on shopgun/turtle#8 trying to make it available as a hex package. `hut` is a transitive dependency of that project and so I would also like to make this project available as a hex package.

Is this something that the maintainers of this project are interested in?
You could publish it by adding a `mix.exs` file or by using the [rebar3 plugin](https://hex.pm/docs/rebar3_usage) for hex publishing. I'd be happy to help out with a PR for either one of those solutions if you are interested. Thanks for all your work making great open source tools :heart: :heart_eyes: :tada:

**Comment by tolbrino** [comment]
@mmmries I thought about doing this before. Feel free to send a PR. Since `hut` uses `erlang.mk` using https://github.com/inaka/hexer.mk might be the way to go?

**Comment by tolbrino** [comment]
Thanks for the effort.

**Comment by tolbrino** [comment]
@mmmries Could you add t@tolbrino.com so I can push the latest version?

**Comment by mmmries** [comment]
👍 added you as a package owner

**Comment by mmmries** [comment]
```
L422-MRies:usaa mmmries$ mix hex.owner list hut
michael@riesd.com
t@tolbrino.com
```

BTW I can remove myself as an owner if you want

**Comment by tolbrino** [comment]
Works, thanks. As for the ownership, as long as you don't plan to do something mad with it feel free to keep the flag.
