### ISSUE TITLE
Configuring hut with standard Erlang application environment

### ISSUE THREAD

**Issue by chemeris** [tolbrino/hut#8]
I'm using `exometer` from an Elixir app and log messages are being repeated twice. I guess I need to configure `hut` to report to `lager`, which is configured to log through `logger`.

The normal way to configure an application in Elixir is though Erlang's application environment. Is it possible to configure `hut` this way?

**Comment by tolbrino** [comment]
You need to configure `hut` to use `lager` at compile-time. There is some reference information in the README file which might help you in your setup.
