### ISSUE TITLE
any example when using rebar3 and setup the logger from a project on top

### ISSUE THREAD

**Issue by benoitc** [tolbrino/hut#9]
I'm wondering if you have any example that show  how to use hut with rebar3  in a library and setup the logger (log library) from the project using the it. Any hint is welcome :)

**Comment by tolbrino** [comment]
I've done similar things using rebar, but not rebar3 yet. Do you have a library as reference I could use to try it myself?

**Comment by benoitc** [comment]
using `overrides` was enough for it. not sure if it needs an  example. this ticket can probably be closed.

**Comment by adamu** [comment]
Compiling on elixir 1.13.4 now produces this warning:

> dependency :hut is using Rebar 2, which is no longer maintained and no longer works in recent Erlang/OTP versions. Remove the :manager option or set it to :rebar3 instead
